#!/bin/bash 

cd /var/lib/apps/post_provision

# login profiles
mkdir -p /etc/profile.d
cp -R etc/profile.d/ /etc/
chmod 644 /etc/profile.d/*
chown root /etc/profile.d/*

# Install scripts
for i in opt/bin/*
do
    s=$(basename $i)
    cp $i /opt/bin/$s
    chmod 755 /opt/bin/$s
done

# Install ssh config and ssh keys
# cp home/core/.ssh/config /home/core/.ssh/config
# for k in home/core/.ssh/authorized_keys.d/*.pub
# do
#     key=$(basename $k)
#     key=${key/_*/}
#     echo "# auto-generated by /var/lib/apps/bin/user-data" > /home/core/.ssh/authorized_keys.d/$key
#     cat $k >> /home/core/.ssh/authorized_keys.d/$key
# done
# update-ssh-keys -u core

# Docker registry credentials
# cp home/core/.dockercfg /home/core/.dockercfg
# chmod 644  /home/core/.dockercfg
# chown core /home/core/.dockercfg
# sudo cp /home/core/.dockercfg /root/.dockercfg
